// Generated by commsdsl2comms v3.3.3

#pragma once

#include <QtCore/QVariantMap>

namespace demo2
{

namespace cc_plugin
{

namespace field
{

QVariantMap createProps_msgId(const char* name, bool serHidden = false);

} // namespace field

} // namespace cc_plugin

} // namespace demo2


